"""delete reletion

Revision ID: 248cab8b5112
Revises: cf35812428f1
Create Date: 2021-04-18 16:40:27.766849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248cab8b5112'
down_revision = 'cf35812428f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_time_created', table_name='posts')
    op.drop_index('ix_posts_time_updated', table_name='posts')
    op.drop_column('posts', 'time_created')
    op.drop_column('posts', 'time_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('time_updated', sa.DATETIME(), nullable=True))
    op.add_column('posts', sa.Column('time_created', sa.DATETIME(), nullable=True))
    op.create_index('ix_posts_time_updated', 'posts', ['time_updated'], unique=False)
    op.create_index('ix_posts_time_created', 'posts', ['time_created'], unique=False)
    # ### end Alembic commands ###
