"""add time

Revision ID: ce333aedffc9
Revises: 248cab8b5112
Create Date: 2021-04-18 16:52:35.728077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce333aedffc9'
down_revision = '248cab8b5112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('time_created', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_time_created'), 'posts', ['time_created'], unique=False)
    op.create_index(op.f('ix_posts_time_updated'), 'posts', ['time_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_time_updated'), table_name='posts')
    op.drop_index(op.f('ix_posts_time_created'), table_name='posts')
    op.drop_column('posts', 'time_updated')
    op.drop_column('posts', 'time_created')
    # ### end Alembic commands ###
